#!/bin/bash
[ "$VERSION" ] || export VERSION="3.11.1"
[ "$FLAVOUR" ] || export FLAVOUR="fglrx"
SHORTVER="${VERSION%.[0-9]*}"
[ -f "bfs-$SHORTVER.patch" ] && export PATCH="bfs-$SHORTVER.patch $PATCH"
./kernel-fglrx-custom.sh
